/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eeedf4",
        "outline": "#757682",
        "on-secondary-container": "#57657b",
        "primary-container": "#1e3a8a",
        "inverse-surface": "#2f3036",
        "secondary-fixed-dim": "#b9c7e0",
        "on-primary-fixed": "#00164e",
        "on-tertiary": "#ffffff",
        "primary": "#00236f",
        "inverse-on-surface": "#f1f0f7",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-fixed": "#341100",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-container": "#90a8ff",
        "secondary": "#515f74",
        "on-surface": "#1a1b21",
        "surface-bright": "#faf8ff",
        "outline-variant": "#c5c5d3",
        "on-surface-variant": "#444651",
        "tertiary": "#4b1c00",
        "surface-dim": "#dad9e1",
        "secondary-fixed": "#d5e3fd",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e7ef",
        "on-tertiary-container": "#f39461",
        "surface-variant": "#e3e1e9",
        "on-tertiary-fixed-variant": "#773205",
        "surface-container-highest": "#e3e1e9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dce1ff",
        "surface-tint": "#4059aa",
        "on-primary-fixed-variant": "#264191",
        "on-secondary-fixed": "#0d1c2f",
        "on-secondary-fixed-variant": "#3a485c",
        "surface-container-low": "#f4f3fa",
        "inverse-primary": "#b6c4ff",
        "tertiary-fixed-dim": "#ffb691",
        "on-background": "#1a1b21",
        "secondary-container": "#d5e3fd",
        "background": "#faf8ff",
        "tertiary-container": "#6e2c00",
        "surface": "#faf8ff",
        "on-error": "#ffffff",
        "warning": "#f59e0b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        xl: "32px",
        "margin-mobile": "16px",
        sm: "8px",
        gutter: "16px",
        "margin-desktop": "48px",
        xs: "4px",
        base: "8px",
        md: "16px",
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
      },
      fontSize: {
        h1: ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      boxShadow: {
        "ambient-sm": "0 2px 8px rgba(0,0,0,0.04)",
        "ambient-md": "0 4px 16px rgba(0,0,0,0.08)",
        "card": "0 4px 24px rgba(0,0,0,0.04)",
      },
    },
  },
  plugins: [],
};
